<?php

namespace Database\Seeders;
use App\Models\UserAccessSubComponentRights;

use Illuminate\Database\Seeder;

class UserAccessSubComponentRightsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        UserAccessSubComponentRights::insert([
            [
            'code'=> '300003001-1',
            'module_code'=> '300',
            'component_code'=> '300003',
            'sub_component_code'=> '300003001',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [
            'code'=> '300003002-1',
            'module_code'=> '300',
            'component_code'=> '300003',
            'sub_component_code'=> '300003002',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [
            'code'=> '300004001-1',
            'module_code'=> '300',
            'component_code'=> '300004',
            'sub_component_code'=> '300004001',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001001-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001001',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001002-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001002',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001003-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001003',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],

            [   
            'code'=> '600001004-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001004',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001005-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001005',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001006-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001006',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001007-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001007',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001008-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001008',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001009-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001009',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001010-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001010',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001011-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001011',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001012-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001012',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001013-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001013',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001014-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001014',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001015-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001015',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600001016-1',
            'module_code'=> '600',
            'component_code'=> '600001',
            'sub_component_code'=> '600001016',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600002001-1',
            'module_code'=> '600',
            'component_code'=> '600002',
            'sub_component_code'=> '600002001',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [   
            'code'=> '600002002-1',
            'module_code'=> '600',
            'component_code'=> '600002',
            'sub_component_code'=> '600002002',
            'user_id'=> '1',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [
            'code'=> '300003001-2',
            'module_code'=> '300',
            'component_code'=> '300003',
            'sub_component_code'=> '300003001',
            'user_id'=> '2',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [
            'code'=> '300003002-3',
            'module_code'=> '300',
            'component_code'=> '300003',
            'sub_component_code'=> '300003002',
            'user_id'=> '3',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],

            [
            'code'=> '300004001-3',
            'module_code'=> '300',
            'component_code'=> '300004',
            'sub_component_code'=> '300004001',
            'user_id'=> '3',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [
            'code'=> '300003001-4',
            'module_code'=> '300',
            'component_code'=> '300003',
            'sub_component_code'=> '300003001',
            'user_id'=> '4',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
            [
            'code'=> '300003001-5',
            'module_code'=> '300',
            'component_code'=> '300003',
            'sub_component_code'=> '300003001',
            'user_id'=> '5',
            'create'=> '1',
            'update'=> '1',
            'delete'=> '1',
            'generate'=> '1',
            'export'=> '1',
            'access_rights'=> '1', 
            'added_by' => env('DEFAULT_USER'),
            'modified_by' => env('DEFAULT_USER')],
        ]);
    }
}
