export const Constants = {
  ACTION_HOME: "ACTION_HOME",
  ACTION_NAVIGATION: "ACTION_NAVIGATION",
  ACTION_QUOTATION: "ACTION_QUOTATION",
  ACTION_REFERENCE: "ACTION_REFERENCE",
  ACTION_LOADING: "ACTION_LOADING",
  ACTION_AUTHENTICATION: "ACTION_AUTHENTICATION",
  ACTION_SALES_DAILY_OUT: "ACTION_SALES_DAILY_OUT",
  ACTION_HUMAN_RESOURCE: "ACTION_HUMAN_RESOURCE",
  ACTION_EPAY_CHECK: "ACTION_EPAY_CHECK",
  ACTION_LOGISTIC: "ACTION_LOGISTIC",
  GET_PRICE_SUCCESS: "GET_PRICE_SUCCESS",
};
