export const Constants = {
  ACTION_HOME: "ACTION_HOME",
  ACTION_NAVIGATION: "ACTION_NAVIGATION",
  ACTION_QUOTATION: "ACTION_QUOTATION",
  ACTION_REFERENCE: "ACTION_REFERENCE",
  ACTION_LOADING: "ACTION_LOADING",
};
